## Lauch Basic EC@2 instance in canada central region.
- name: Ansible Play
  hosts: localhost
  tasks:
  - name:   launching AWS instance using Ansible

    ec2:
      key_name: jenkins-web
      region: ca-central-1
      instance_type: t2.micro
      image: ami-08947f251e1b8f3b9
      instance_tags:
        Name: Demo_server
