- name: Start instances
  hosts: localhost
  tasks:
    - name: Start instances that were previously Stoped
      ec2:
        state: running
        region: ca-central-1
        instance_tags:
           Name: Demo_server
