- name: Terminate instances
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously created
      ec2:
        state: absent
        region: ca-central-1
        instance_ids: i-07f8cd086f8f60647
